/**
 * The demo corpus — entirely fictional.
 *
 * Nobody in here exists. It is hand-written so the demo report has something
 * honest to chew on: a real 3am habit, a situationship that burned out in four
 * months, a chat that quietly died in 2020, an argument with a full arc, and
 * enough dated slang in the early years for The Ick to have material.
 *
 * Timestamps are constructed in local time on purpose. `new Date(y, m, d, 3, 22)`
 * is 3:22am for whoever is looking at the page, so the authored hour is the hour
 * the engine scores and the hour the UI prints, in every timezone.
 */

import type { DramaMessage } from "./types";

/** [dayOffset, hour, minute, isSelf, text] */
type Seed = readonly [number, number, number, 0 | 1, string];

interface SeedThread {
  conversation: string;
  platform: string;
  /** [year, monthIndex, day] the day offsets count from. */
  anchor: readonly [number, number, number];
  seeds: readonly Seed[];
}

export const TEMPLATE_OWNER = "you";

const THREADS: readonly SeedThread[] = [
  {
    conversation: "maya.kh",
    platform: "Snapchat",
    anchor: [2019, 1, 14],
    seeds: [
      [0, 22, 14, 0, "ok so you'll never guess who just added me back"],
      [0, 22, 15, 1, "no way"],
      [0, 22, 15, 1, "MAYA. who"],
      [0, 22, 19, 0, "guess"],
      [0, 22, 20, 1, "i will block you"],
      [0, 22, 22, 0, "sami. after two years of nothing. two YEARS"],
      [0, 22, 23, 1, "im deceased"],
      [0, 22, 24, 1, "that is so cray cray"],
      [3, 1, 42, 1, "cant sleep. do you ever think about how weird it is that we just decided to be friends in year 9 and never stopped"],
      [3, 1, 48, 0, "its 2am babe"],
      [3, 1, 49, 0, "but yes. constantly"],
      [12, 19, 3, 0, "did you hear about rana"],
      [12, 19, 4, 1, "no???"],
      [12, 19, 6, 0, "dont tell anyone i told you. she's been seeing him since january"],
      [12, 19, 7, 1, "SINCE JANUARY"],
      [12, 19, 7, 1, "and she sat in my car for 40 minutes last week and said nothing"],
      [40, 23, 51, 1, "yolo i guess"],
      [40, 23, 52, 0, "never say that again"],
      [128, 3, 11, 1, "are you awake"],
      [128, 3, 12, 1, "obviously not. anyway i just reread our chat from march and we were unwell"],
      [128, 9, 2, 0, "i was asleep like a normal person. what did we say"],
      [128, 9, 6, 1, "im not repeating it. some things should stay in 2019"],
      [301, 20, 40, 0, "how are you actually. not the version you tell everyone"],
      [301, 20, 55, 1, "bad. but manageable bad"],
      [301, 20, 56, 0, "thats not an answer thats a press release"],
      [301, 21, 8, 1, "ok. bad. i dont think he's coming back this time and the worst part is im relieved"],
      [301, 21, 9, 0, "then thats not the worst part. thats the answer"],
      [560, 2, 30, 1, "i keep drafting the message and deleting it"],
      [560, 2, 31, 1, "like 14 times tonight"],
      [560, 2, 33, 1, "you're asleep. ignore me"],
      [560, 10, 12, 0, "i was asleep. do NOT send it"],
      [560, 10, 14, 1, "i sent it"],
      [560, 10, 14, 0, "MAYA"],
      [899, 18, 22, 0, "guess who's engaged"],
      [899, 18, 23, 1, "if you say rana i'm walking into the sea"],
      [899, 18, 24, 0, "rana"],
      [1240, 1, 15, 1, "why am i awake. why are YOU awake"],
      [1240, 1, 16, 0, "solidarity"],
      [1240, 1, 22, 1, "genuinely though thank you for the last five years. i know i say it at 1am which makes it less credible"],
      [1240, 1, 24, 0, "it makes it more credible. nobody lies at 1am, they just get honest badly"],
      [1500, 13, 5, 0, "did you see what she posted"],
      [1500, 13, 40, 1, "i saw. i'm being normal about it"],
      [1500, 13, 41, 0, "you have never been normal about anything"],
      [1780, 3, 3, 1, "ok so. hypothetically. if someone texted their ex at 3am"],
      [1780, 3, 4, 0, "hypothetically i would come to your house"],
      [1780, 3, 4, 1, "hypothetically its already sent"],
      [1990, 21, 12, 0, "i'm sorry about last week. i was being a lot and you took the whole thing"],
      [1990, 21, 30, 1, "you were being a lot. i'd take it again"],
      [2150, 2, 44, 1, "cant sleep again. i think i'm just someone who's awake now"],
      [2150, 2, 51, 0, "you are someone who is awake now. i'll be up in four hours, tell me everything then"],
      [2290, 17, 2, 0, "seven years of this chat. do you realise how much evidence is in here"],
      [2290, 17, 4, 1, "please never let anyone read it"],
      [2290, 17, 5, 0, "i'm having it printed"],
      [2320, 12, 30, 1, "lunch friday?"],
      [2320, 12, 47, 0, "always"],
    ],
  },
  {
    conversation: "the coven 🔮",
    platform: "Instagram",
    anchor: [2021, 5, 5],
    seeds: [
      [0, 20, 1, 0, "EMERGENCY MEETING"],
      [0, 20, 2, 1, "what happened"],
      [0, 20, 2, 0, "check her story. now. i'll wait"],
      [0, 20, 5, 1, "no way"],
      [0, 20, 5, 1, "NO WAY"],
      [0, 20, 9, 0, "apparently they've been in dubai together the whole week"],
      [0, 20, 11, 1, "and she told me she was at her mums"],
      [0, 20, 12, 0, "she told me she had covid"],
      [0, 20, 13, 1, "she told rana she was on a work trip. this woman has three alibis"],
      [1, 0, 22, 1, "i cannot sleep i keep thinking about the dubai thing"],
      [1, 0, 23, 0, "same. we are being insane"],
      [1, 0, 40, 1, "screenshot everything. i'm serious"],
      [45, 19, 30, 0, "did you hear about the wedding"],
      [45, 19, 31, 1, "which wedding"],
      [45, 19, 32, 0, "exactly"],
      [120, 22, 15, 1, "guess who just liked a photo from 2018"],
      [120, 22, 16, 0, "no he did NOT"],
      [120, 22, 17, 1, "he did. 2018. that's not an accident that's an excavation"],
      [220, 2, 5, 1, "ok its 2am and i have a theory"],
      [220, 2, 6, 1, "hear me out"],
      [220, 2, 8, 1, "she never actually left. she just muted us"],
      [220, 9, 44, 0, "you cannot be doing forensics at 2am"],
      [400, 18, 12, 0, "whatever. i'm done defending her"],
      [400, 18, 30, 1, "thats fair honestly"],
      [401, 13, 2, 0, "i was harsh yesterday. sorry. it wasn't about her"],
      [401, 13, 20, 1, "we know"],
      [610, 21, 44, 1, "apparently they broke up. dont tell anyone i told you"],
      [610, 21, 45, 0, "we are a group chat. that is structurally impossible"],
      [800, 3, 18, 1, "u up"],
      [800, 3, 19, 0, "unfortunately"],
      [800, 3, 25, 1, "i think i made a mistake and i need three witnesses"],
      [800, 3, 26, 0, "we're here. go"],
      [1010, 20, 3, 0, "five years of this group chat and not one screenshot has leaked. we are professionals"],
      [1010, 20, 5, 1, "the archive is sacred"],
      [1180, 1, 12, 1, "cant sleep. reading old messages. we were so young and so unwell"],
      [1180, 1, 13, 0, "we are currently unwell"],
      [1180, 1, 14, 1, "yes but stylishly now"],
      [1340, 16, 22, 0, "guess who's back in town"],
      [1340, 16, 23, 1, "i am not emotionally equipped"],
      [1340, 16, 40, 1, "what time"],
      [1400, 19, 5, 0, "dinner saturday, no phones, i'm serious"],
      [1400, 19, 6, 1, "you say that every time and you film everything"],
      [1400, 19, 8, 0, "documentation is different"],
    ],
  },
  {
    conversation: "d.zayn___",
    platform: "Snapchat",
    anchor: [2021, 8, 11],
    seeds: [
      [0, 23, 40, 1, "hey. i know its late"],
      [0, 23, 52, 0, "its fine. whats up"],
      [1, 0, 14, 1, "i've been trying to say this for a week and i keep chickening out"],
      [1, 0, 16, 1, "i like you. like properly. i needed to tell you before i talked myself out of it again"],
      [1, 0, 41, 0, "i know. i've known for a while"],
      [1, 0, 42, 1, "thats not an answer"],
      [1, 0, 58, 0, "i know that too"],
      [8, 2, 12, 1, "cant sleep"],
      [8, 2, 13, 0, "same. call?"],
      [30, 3, 5, 1, "are you awake"],
      [30, 3, 22, 0, "i am now"],
      [30, 3, 24, 1, "come over"],
      [64, 21, 3, 1, "so are we going to talk about saturday or are we doing the thing where we don't"],
      [64, 22, 40, 0, "we're doing the thing where we don't"],
      [70, 19, 12, 1, "you always do this"],
      [70, 19, 13, 1, "you go completely silent and then act surprised that i'm upset"],
      [70, 19, 14, 1, "hello???"],
      [70, 23, 50, 0, "i was at work. calm down"],
      [70, 23, 51, 1, "don't tell me to calm down"],
      [88, 2, 30, 1, "why are you ignoring me"],
      [88, 2, 31, 1, "i can see you've been online"],
      [88, 2, 44, 1, "ok then"],
      [90, 18, 2, 0, "i'm sorry. i'm bad at this and you deserve better than the version of me that goes quiet"],
      [90, 18, 30, 1, "i don't want a better version i want the actual one to answer his phone"],
      [90, 18, 45, 0, "thats fair"],
      [112, 1, 8, 1, "this is the third time this month"],
      [112, 1, 9, 1, "you never actually say anything you just wait for me to get tired of asking"],
      [112, 1, 30, 0, "thats not what i said"],
      [112, 1, 31, 1, "thats exactly what you did"],
      [140, 20, 15, 0, "we need to talk"],
      [140, 20, 40, 1, "say it here. i'm not doing the in person version so you can watch my face"],
      [140, 21, 12, 0, "i can't do this anymore. i'm not okay and i'm making you not okay"],
      [140, 21, 30, 1, "so thats it"],
      [140, 21, 55, 0, "i think so"],
      [141, 3, 2, 1, "i'm not going to beg. i just want you to know that i was honest with you the whole time and you were never once honest back"],
      [141, 3, 4, 1, "thats the part i'll be annoyed about in five years"],
      [143, 2, 51, 1, "sorry. that was a lot. i shouldn't have sent it at 3am"],
      [143, 2, 52, 1, "im not sorry about the content just the timing"],
      [160, 4, 12, 1, "delete this after you read it"],
      [160, 4, 14, 1, "i miss you and i'm furious that i miss you"],
      [163, 11, 30, 0, "i read it. i'm not going to make it worse by answering properly"],
      [201, 1, 44, 1, "u up"],
      [201, 1, 45, 1, "ignore that"],
      [201, 1, 46, 1, "seriously ignore that"],
      [430, 3, 22, 0, "u up"],
      [430, 3, 41, 1, "you cannot be serious"],
      [430, 3, 43, 0, "i've been trying to send this for eight months"],
      [430, 3, 55, 1, "i'm going to say something kind and then i'm going to block you, because both of those are true"],
      [430, 4, 2, 1, "i hope you're actually okay. i mean that. lose my number"],
      [431, 14, 30, 0, "understood. take care of yourself"],
    ],
  },
  {
    conversation: "noor.hbb",
    platform: "Instagram",
    anchor: [2023, 4, 2],
    seeds: [
      [0, 14, 22, 0, "your story made me laugh out loud in a meeting so thanks for that"],
      [0, 14, 40, 1, "thats the entire point of the account"],
      [1, 23, 12, 0, "ok this is going to sound insane but are you free thursday"],
      [1, 23, 14, 1, "it does sound insane. yes"],
      [4, 1, 3, 1, "cant sleep. thursday was ridiculous"],
      [4, 1, 4, 0, "ridiculous good?"],
      [4, 1, 5, 1, "ridiculous good"],
      [6, 2, 40, 0, "are you awake"],
      [6, 2, 41, 1, "unfortunately yes"],
      [6, 2, 55, 0, "i havent stopped thinking about you and i'm slightly annoyed about it"],
      [9, 3, 12, 1, "i'm outside"],
      [9, 3, 13, 0, "you're WHAT"],
      [12, 22, 30, 1, "dont tell anyone about this yet. i want one thing that isn't a group chat topic"],
      [12, 22, 33, 0, "deal. it stays between us"],
      [20, 1, 2, 1, "i've never told anyone this"],
      [20, 1, 8, 1, "i genuinely thought i was done doing this. like i'd retired"],
      [20, 1, 20, 0, "you're the least retired person i've ever met"],
      [28, 2, 15, 0, "wyd"],
      [28, 2, 16, 1, "spiralling. you?"],
      [28, 2, 16, 0, "same. want to spiral in the same room"],
      [35, 20, 4, 1, "so are you going to tell me what we're doing or are we just going to keep being extremely normal about it"],
      [35, 21, 50, 0, "can we not do the labels thing"],
      [35, 21, 51, 1, "thats an answer, its just not the one you think you gave"],
      [44, 3, 30, 1, "u up"],
      [44, 3, 32, 1, "forget it"],
      [51, 19, 12, 0, "sorry i went quiet. work has been insane"],
      [51, 19, 40, 1, "its been nine days"],
      [51, 19, 41, 0, "i know"],
      [58, 1, 22, 1, "i keep defending you to people who havent even accused you of anything. thats probably a bad sign"],
      [58, 1, 23, 1, "you there"],
      [58, 1, 40, 1, "guess not"],
      [60, 14, 2, 0, "i'm sorry. i'm genuinely bad at this and you keep being lovely about it which makes it worse"],
      [60, 14, 30, 1, "i'm going to stop being lovely about it soon, just so you can plan"],
      [72, 2, 3, 0, "are you awake. i want to say something and i'll lose my nerve by morning"],
      [72, 2, 20, 1, "i'm awake"],
      [72, 2, 44, 0, "i think i've been treating you like a sure thing and you've never once acted like one and i dont know what to do with that"],
      [72, 2, 55, 1, "you could just be normal about it. thats an option nobody ever picks"],
      [80, 23, 12, 1, "did you see the thing rana posted"],
      [80, 23, 30, 0, "i saw. i'm not commenting"],
      [88, 1, 30, 1, "we need to talk and i hate that i'm the one saying it"],
      [88, 2, 2, 0, "i know. i've been waiting for you to say it so i wouldn't have to"],
      [88, 2, 3, 1, "wow ok"],
      [88, 2, 4, 1, "thats actually the meanest thing you've said and you said it so calmly"],
      [88, 2, 30, 0, "thats fair. i'm sorry"],
      [96, 3, 12, 1, "last thing and then i'm done. i wasnt asking for much. i was asking for the bare minimum in a nice font"],
      [96, 3, 30, 0, "i know"],
      [104, 21, 2, 0, "hope you're ok"],
      [104, 21, 40, 1, "i am. dont do this in four months"],
      [104, 21, 41, 0, "ok"],
      [112, 2, 15, 0, "u up"],
      [112, 2, 40, 1, "you said ok"],
    ],
  },
  {
    conversation: "layla_zzz",
    platform: "Snapchat",
    anchor: [2019, 3, 20],
    seeds: [
      [0, 16, 12, 0, "hiii omg it's been forever"],
      [0, 16, 13, 1, "LAYLA. how are you"],
      [0, 16, 20, 0, "living my best life honestly. squad goals energy"],
      [0, 16, 22, 1, "please never type that again"],
      [0, 16, 23, 0, "netflix and chill is also back apparently"],
      [0, 16, 24, 1, "im leaving"],
      [2, 21, 3, 1, "ok but what happened with the thing"],
      [2, 21, 30, 0, "which thing"],
      [2, 21, 31, 1, "THE thing"],
      [2, 21, 44, 0, "oh. dont tell anyone. it's still happening"],
      [14, 22, 15, 1, "hbu, still doing the course?"],
      [14, 22, 40, 0, "dropped it. long story. ttyl"],
      [30, 1, 22, 1, "cant sleep, thinking about that trip we said we'd do"],
      [30, 1, 40, 0, "we should actually do it"],
      [30, 1, 41, 1, "we say that every year"],
      [30, 1, 42, 0, "and every year we mean it. thats what counts"],
      [61, 19, 3, 0, "did you hear about sami"],
      [61, 19, 4, 1, "no what"],
      [61, 19, 12, 0, "apparently he's moving. like properly moving"],
      [90, 20, 30, 1, "hey! how did the interview go"],
      [92, 11, 2, 0, "sorry! just seeing this. it went ok i think"],
      [130, 2, 12, 1, "u up"],
      [130, 2, 13, 1, "i had a dream we were 16 again and it was extremely upsetting"],
      [131, 15, 30, 0, "sorry i missed this. that's so weird i had a similar one"],
      [180, 18, 2, 1, "long time. how are you actually"],
      [182, 20, 30, 0, "sorryyy i'm the worst at replying. i'm ok! busy"],
      [182, 20, 31, 1, "you are genuinely the worst at replying"],
      [182, 20, 40, 0, "i know. i'm working on it"],
      [240, 21, 15, 1, "happy birthday!! hope it's a good one"],
      [241, 9, 3, 0, "thank youuu sorry just seeing"],
      [300, 22, 40, 1, "did you see the group chat"],
      [303, 14, 12, 0, "just caught up. wild"],
      [340, 19, 22, 1, "we still owe each other that trip"],
      [341, 20, 3, 0, "we do!! lets actually plan it"],
      [341, 20, 4, 1, "ok putting dates in now"],
      [370, 18, 30, 1, "did the dates work?"],
      [372, 12, 15, 0, "sorry! things got mad. can we do next month"],
      [372, 12, 20, 1, "of course"],
      [405, 21, 3, 1, "hey! checking in. no pressure"],
      [407, 10, 30, 0, "sorry. i've been really bad lately. i'll explain properly soon"],
      [407, 10, 44, 1, "whenever you're ready. i'm not going anywhere"],
      [430, 20, 12, 1, "still here whenever you want to talk"],
    ],
  },
  {
    conversation: "sami.exe",
    platform: "Instagram",
    anchor: [2019, 7, 3],
    seeds: [
      [0, 17, 3, 0, "yo"],
      [0, 17, 4, 1, "yo"],
      [0, 17, 5, 0, "that photo you posted is on fleek ngl"],
      [0, 17, 6, 1, "i am begging you to stop"],
      [0, 17, 12, 0, "swag"],
      [3, 23, 40, 1, "are you coming saturday or not, i need a number for the table"],
      [4, 12, 2, 0, "yeah yeah i'm in"],
      [11, 21, 3, 1, "you didn't come saturday"],
      [11, 21, 30, 0, "my bad. something came up"],
      [11, 21, 31, 1, "you said that last time"],
      [11, 21, 40, 0, "i know. i'm sorry"],
      [60, 2, 12, 0, "u up"],
      [60, 2, 30, 1, "why are you like this"],
      [60, 2, 31, 0, "cant sleep. genuine question, are you mad at me"],
      [60, 2, 50, 1, "not mad. just tired of being the one who organises everything and then gets stood up"],
      [61, 13, 3, 0, "thats fair. i've been a bad friend this year and i know exactly why and i'm not going to make it your problem"],
      [61, 13, 30, 1, "you can make it my problem a little. thats what this is"],
      [120, 20, 15, 0, "i'm sorry about august. properly sorry, not the version where i say it and change the subject"],
      [120, 20, 40, 1, "i appreciate that"],
      [120, 20, 41, 0, "it won't happen again"],
      [220, 19, 2, 1, "it happened again"],
      [220, 19, 30, 0, "yeah"],
      [340, 22, 3, 0, "did you hear about layla"],
      [340, 22, 4, 1, "no?"],
      [340, 22, 12, 0, "dont tell anyone. she's been having a rough one"],
      [340, 22, 30, 1, "i've been texting her, she's not really answering"],
      [500, 1, 22, 0, "cant sleep. do you ever think we peaked in 2019"],
      [500, 1, 40, 1, "we did not peak in 2019, we just had more free time"],
      [500, 1, 41, 0, "thats the same thing"],
      [700, 18, 3, 1, "moving day still saturday?"],
      [700, 18, 40, 0, "yes! come, bring nothing, i have too much stuff"],
      [860, 20, 12, 0, "i'm sorry i was so unreliable for like three years. i'm better now, mostly"],
      [860, 20, 30, 1, "you are better now. mostly"],
      [860, 20, 31, 0, "i'll take mostly"],
    ],
  },
];

function timestampFor(
  anchor: readonly [number, number, number],
  dayOffset: number,
  hour: number,
  minute: number,
): number {
  const [year, monthIndex, day] = anchor;
  return new Date(year, monthIndex, day + dayOffset, hour, minute, 0, 0).getTime();
}

/**
 * Materialize the fictional corpus. Ids are assigned in a stable order so the
 * demo report is identical on every render.
 */
export function buildTemplateMessages(): DramaMessage[] {
  const messages: DramaMessage[] = [];
  let id = 1;

  for (const thread of THREADS) {
    for (const [dayOffset, hour, minute, isSelf, text] of thread.seeds) {
      messages.push({
        id: id++,
        platform: thread.platform,
        conversation: thread.conversation,
        sender: isSelf === 1 ? TEMPLATE_OWNER : thread.conversation,
        sentAtMs: timestampFor(thread.anchor, dayOffset, hour, minute),
        text,
        isSelf: isSelf === 1,
      });
    }
  }

  return messages.sort(
    (left, right) => left.sentAtMs - right.sentAtMs || left.id - right.id,
  );
}

/** Conversation labels in the demo, for redaction and for the landing preview. */
export const TEMPLATE_CONVERSATIONS: readonly string[] = THREADS.map(
  (thread) => thread.conversation,
);

export const TEMPLATE_PLATFORMS: readonly string[] = [
  ...new Set(THREADS.map((thread) => thread.platform)),
];
